services:
  - type: worker
    name: botforgev1-worker
    env: python
    buildCommand: pip install -r BotForge/requirements.txt
    startCommand: python BotForge/main.py
    plan: starter
    autoDeploy: true
  - type: web
    name: botforgev1-dashboard
    env: python
    buildCommand: pip install -r BotForge/requirements.txt
    startCommand: uvicorn BotForge.dashboard_app:app --host 0.0.0.0 --port $PORT
    plan: starter
    autoDeploy: true
